version: '3'
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  db_admin:
    image: mrvautin/adminmongo
    restart: "always"
    environment:
      - CONN_NAME=whatever
      - DB_HOST=mongodb
      - DB_PORT=27017
    ports:
      - "1234:1234"
    links:
      - db

  cbt_ideas:
    # restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        NODE_ENV: develop
    volumes:
      - '../src:/srv/app/src'
      - '../ui:/srv/app/ui'
      - '../test:/srv/app/test'
      - '../static:/srv/app/static'
      - '../package.json:/srv/app/package.json'
    environment:
      NODE_ENV: develop
    links:
      - db
    ports:
     - "3006:3000"

volumes:
  db:
  db_admin:
  cbt_ideas: